image: maven:3.6.3-jdk-11

services:
  - docker:dind

variables:
  MAVEN_CLI_OPTS: "-s settings.xml"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - ~/.m2/repository
    - target/

stages:
  - build
  - deploy

build_feature:
  stage: build
  script:
    - mvn ${MAVEN_CLI_OPTS} clean install -Dskip.assembly.release.docker=true
  except:
    refs:
      - master

deploy_artifacts:
  stage: deploy
  script:
    - mvn ${MAVEN_CLI_OPTS} clean install deploy
  only:
    refs:
      - master
